FROM node:16-alpine

WORKDIR /usr/src/app

COPY . .

RUN npm ci

ENV PORT=${PORT}
ENV DB_SERVER_HOSTNAME=${DB_SERVER_HOSTNAME}
ENV DB_SERVER_USERNAME=${DB_SERVER_USERNAME}
ENV DB_SERVER_PASSWORD=${DB_SERVER_PASSWORD}
ENV DB_SERVER_PORT=${DB_SERVER_PORT}
ENV DB_SERVER_NAME=${DB_SERVER_NAME}
ENV DB_MIN_POOLS=${DB_MIN_POOLS}
ENV DB_MAX_POOLS=${DB_MAX_POOLS}

RUN npm run build

EXPOSE 8080
CMD ["npm", "run", "start:prod"]